"""p0_trip_revision_append_only_and_proposal_hardening

Revision ID: 104a12968f33
Revises: 6df9257fef72
Create Date: 2026-10-04 00:42:14.747669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104a12968f33'
down_revision: Union[str, Sequence[str], None] = '6df9257fef72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('total_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('travellers',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_constraint('ck_itinerary_dates', 'itineraries', type_='check')
    op.drop_constraint('ck_itinerary_travellers', 'itineraries', type_='check')
    op.drop_constraint('ck_itinerary_budget', 'itineraries', type_='check')

    op.create_check_constraint(
        'ck_itinerary_dates',
        'itineraries',
        'start_date IS NULL OR end_date IS NULL OR end_date >= start_date'
    )
    op.create_check_constraint(
        'ck_itinerary_travellers',
        'itineraries',
        'travellers IS NULL OR travellers >= 1'
    )
    op.create_check_constraint(
        'ck_itinerary_budget',
        'itineraries',
        'total_budget IS NULL OR total_budget >= 0'
    )

    with op.batch_alter_table('trip_proposals', schema=None) as batch_op:
        batch_op.create_index('ix_trip_proposals_trip_created', ['trip_id', 'created_at'], unique=False)
        batch_op.create_index('ix_trip_proposals_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restored_from_version', sa.Integer(), nullable=True))
        batch_op.create_index('ix_trip_snapshots_trip_created', ['trip_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_trip_snapshots_trip_created')
        batch_op.drop_column('restored_from_version')

    with op.batch_alter_table('trip_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_trip_proposals_user_created')
        batch_op.drop_index('ix_trip_proposals_trip_created')

    op.drop_constraint('ck_itinerary_dates', 'itineraries', type_='check')
    op.drop_constraint('ck_itinerary_travellers', 'itineraries', type_='check')
    op.drop_constraint('ck_itinerary_budget', 'itineraries', type_='check')

    op.create_check_constraint('ck_itinerary_dates', 'itineraries', 'end_date >= start_date')
    op.create_check_constraint('ck_itinerary_travellers', 'itineraries', 'travellers >= 1')
    op.create_check_constraint('ck_itinerary_budget', 'itineraries', 'total_budget >= 0')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('travellers',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
