"""add_trip_proposals_and_parent_revisions

Revision ID: 6df9257fef72
Revises: e766197b12d3
Create Date: 2026-10-04 00:07:02.456852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df9257fef72'
down_revision: Union[str, Sequence[str], None] = 'e766197b12d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=False),
    sa.Column('after_state', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'expired')", name='ck_trip_proposal_status'),
    sa.CheckConstraint('parent_version >= 1', name='ck_proposal_parent_version'),
    sa.ForeignKeyConstraint(['trip_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_proposals', schema=None) as batch_op:
        batch_op.create_index('ix_trip_proposals_trip_status', ['trip_id', 'status'], unique=False)

    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_version', sa.Integer(), nullable=True))

    op.create_check_constraint(
        'ck_booking_provenance',
        'bookings',
        "provenance IN ('USER_PROVIDED', 'SAVED_REFERENCE', 'CURATED', 'PARTNER_VERIFIED', 'PROVIDER_VERIFIED')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_booking_provenance', 'bookings', type_='check')

    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.drop_column('parent_version')

    with op.batch_alter_table('trip_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_trip_proposals_trip_status')

    op.drop_table('trip_proposals')
    # ### end Alembic commands ###

