"""harden_snapshots_vouchers_and_temporal

Revision ID: 8d8609917cb1
Revises: c1bcb4ec0acc
Create Date: 2026-10-03 22:43:20.479326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8609917cb1'
down_revision: Union[str, Sequence[str], None] = 'c1bcb4ec0acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward_vouchers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('actor_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instruction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('instruction')
        batch_op.drop_column('actor_type')
        batch_op.drop_column('action_type')

    with op.batch_alter_table('reward_vouchers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
