"""initial_dashtiny_schema

Revision ID: c1bcb4ec0acc
Revises: 
Create Date: 2026-10-03 22:24:51.497623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bcb4ec0acc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_redemptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('voucher_id', sa.String(length=36), nullable=False),
    sa.Column('coins_spent', sa.Integer(), nullable=False),
    sa.Column('voucher_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['reward_vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'voucher_id', name='uq_user_voucher_redemption')
    )
    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.create_index('ix_reward_redemptions_user', ['user_id', 'redeemed_at'], unique=False)

    op.create_table('reward_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_transactions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index('ix_reward_tx_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('trip_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('days_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'version', name='uq_trip_snapshot_version')
    )
    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_trip_snapshots_trip_ver', ['trip_id', 'version'], unique=False)

    op.create_table('post_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_user_like')
    )
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_runs_trip_created', ['trip_id', 'created_at'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_pnr_ref_key'), type_='unique')
        batch_op.alter_column('pnr_ref', existing_type=sa.VARCHAR(length=50), nullable=True)
        batch_op.create_index('ix_bookings_trip_created', ['trip_id', 'created_at'], unique=False)
        batch_op.create_index('ix_bookings_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_unique_constraint('uq_provider_pnr_ref', ['provider', 'pnr_ref'])

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('source_trip_id', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_community_posts_created', ['created_at'], unique=False)
        batch_op.create_index('ix_community_posts_source_trip', ['source_trip_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'itineraries', ['source_trip_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('source_trip_id', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_itineraries_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index('ix_itineraries_owner_status_date', ['owner_id', 'status', 'start_date'], unique=False)
        batch_op.create_foreign_key(None, 'itineraries', ['source_trip_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('itinerary_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('end_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transit_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transit_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transit_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transit_confidence', sa.String(length=50), nullable=True))
        batch_op.create_index('ix_activity_day_sort', ['day_id', 'sort_order'], unique=False)

    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.create_index('ix_itinerary_days_itinerary_day', ['itinerary_id', 'day_number'], unique=False)
        batch_op.create_unique_constraint('uq_itinerary_day_number', ['itinerary_id', 'day_number'])

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_price_alerts_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.drop_column('accuracy_percentage')

    with op.batch_alter_table('sanctuaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('price_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_nights', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_source', sa.String(length=50), nullable=True))

    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_squad_member', ['squad_id', 'user_id'])

    with op.batch_alter_table('squad_rooms', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['itinerary_id'])

    with op.batch_alter_table('traveler_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('source_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_explicit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_traveler_memories_user_cat_key', ['user_id', 'category', 'key'], unique=False)
        batch_op.create_unique_constraint('uq_user_memory_key', ['user_id', 'category', 'key'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_completion_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_booking_count', sa.Integer(), nullable=True))
        batch_op.alter_column('trust_score',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="95.0")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('trust_score',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('verified_booking_count')
        batch_op.drop_column('trip_completion_count')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('traveler_memories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_memory_key', type_='unique')
        batch_op.drop_index('ix_traveler_memories_user_cat_key')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('is_explicit')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('source')

    with op.batch_alter_table('squad_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_squad_member', type_='unique')

    with op.batch_alter_table('sanctuaries', schema=None) as batch_op:
        batch_op.drop_column('rating_source')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating_value')
        batch_op.drop_column('duration_nights')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('price_unit')
        batch_op.drop_column('price_currency')
        batch_op.drop_column('price_amount')

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy_percentage', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_price_alerts_user_active')

    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.drop_constraint('uq_itinerary_day_number', type_='unique')
        batch_op.drop_index('ix_itinerary_days_itinerary_day')

    with op.batch_alter_table('itinerary_activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_day_sort')
        batch_op.drop_column('transit_confidence')
        batch_op.drop_column('transit_source')
        batch_op.drop_column('transit_mode')
        batch_op.drop_column('transit_minutes')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('timezone')
        batch_op.drop_column('end_at')
        batch_op.drop_column('start_at')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_itineraries_owner_status_date')
        batch_op.drop_index('ix_itineraries_owner_created')
        batch_op.drop_column('source_trip_id')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_community_posts_source_trip')
        batch_op.drop_index('ix_community_posts_created')
        batch_op.drop_column('source_trip_id')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_provider_pnr_ref', type_='unique')
        batch_op.drop_index('ix_bookings_user_created')
        batch_op.drop_index('ix_bookings_trip_created')
        batch_op.create_unique_constraint(batch_op.f('bookings_pnr_ref_key'), ['pnr_ref'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_runs_trip_created')

    op.drop_table('post_likes')
    with op.batch_alter_table('trip_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_trip_snapshots_trip_ver')

    op.drop_table('trip_snapshots')
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_reward_tx_user_created')
        batch_op.drop_index(batch_op.f('ix_reward_transactions_idempotency_key'))

    op.drop_table('reward_transactions')
    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.drop_index('ix_reward_redemptions_user')

    op.drop_table('reward_redemptions')
    # ### end Alembic commands ###
